logging:
  level:
    openmart:
      apigateway:
        api: DEBUG
  path: "/tank0/logs"

zuul:
  routes:
  open-mart-api:
      path: /v1/mart/**
      url: http://localhost:8082
      stripPrefix: false
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 10000

management:
  endpoints:
    web:
      exposure:
        include: "refresh, env"